{% set name = "simpleitk" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: a551636e5d33dff88818bdb2fdaba190184b225d0eee015bfa2ce3a4fb6bdb24

build:
  number: 1
  skip: true  # [ win and py27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake   >=3.15
    - ninja
    - swig    4.0.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - libitk
    - libsimpleitk ={{ version }}
    - fftw

  run:
    - vs2015_runtime  # [win]
    - {{ pin_compatible('libitk-devel', exact=True) }}
    - python

test:
  imports:
    - SimpleITK

about:
  home: http::/www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
