{% set name = "simpleitk" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: 9edc56b81a9f295081da2f6cafce4f7f5f3b4cfc6b8cb33365e68b581daea1d2

build:
  number: 1

requirements:
  build:
    - cmake   >=3.15
    - ninja
    - swig    4.0.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - libitk-devel
    - libsimpleitk ={{ version }}
    - fftw

  run:
    - vs2015_runtime  # [win]
    - {{ pin_compatible('libitk-devel', exact=True) }}
    - python

test:
  imports:
    - SimpleITK

about:
  home: http://www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
