{% set name = "simpleitk" %}
{% set version = "2.1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: f52f8906bc5350e1ea8e7b163ef9242ca7e52de5c53c51793ea7539c42014748
  patches:                 # [build_platform != target_platform]
    - version_setup.patch  # [build_platform != target_platform]
    # see https://github.com/conda-forge/simpleitk-feedstock/pull/27#issuecomment-1264707645
    - undefined-lookup-python.patch  # [(build_platform != target_platform) and osx]

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake   >=3.15
    - ninja
    - swig    4.0.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - libitk
    - libitk-devel
    - libsimpleitk ={{ version }}
    - fftw

  run:
    - vs2015_runtime  # [win]
    - {{ pin_compatible('libitk', exact=True) }}
    - {{ pin_compatible('libitk-devel', exact=True) }}
    - python

test:
  imports:
    - SimpleITK

about:
  home: http://www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
