{% set version = "2.4.0" %}

package:
  name: simpleitk
  version: {{ version }}

source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{ version }}/SimpleITK-{{ version }}.tar.gz
  sha256: bcf9e3b7f944b049728a72ca99d122d3849802626bc41e8ba14b5498cd218df5

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake   >=3.16.3
    - ninja
    - swig    4.2.*
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}


  host:
    - python
    - pip
    - libsimpleitk ={{ version }}
    - libitk-devel

  run:
    - python

test:
  imports:
    - SimpleITK

about:
  home: http://www.simpleitk.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
  recipe-maintainers:
    - blowekamp
    - zivy
